#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_DIR=$SCRIPT_DIR/..

if [ -f "$PROJECT_DIR/env/.env" ]
then
    source "$PROJECT_DIR/.env"
fi

if ! command -v cfn-lint &> /dev/null
then
    pip install -r $PROJECT_DIR/requirements.txt
fi

cfn-lint $PROJECT_DIR/templates/*.yml